/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudapp.Frame;

import crudapp.Controller.IncomingController;
import crudapp.Helper.Helper;
import crudapp.Logic.Logic;
import crudapp.Model.MainModel;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class Incoming extends javax.swing.JFrame {

	MainModel model = new MainModel();
	Logic logic = new Logic();
	IncomingController controller = new IncomingController();
	public String goods_id;
	Helper helper = new Helper();
	ResultSet rs;

	public void search(String type, String query) {
		try {
			if (query.isEmpty()) {
				this.rs = controller.get();
			} else if (type.equals("id") && !query.isEmpty()) {
				this.rs = controller.showById(query);
			} else if (type.equals("name") && !query.isEmpty()) {
				this.rs = controller.showByName(query);
			}

			loadTable(this.rs);
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}
	
	public void refresh(){
		clear();
		tf_name.setEnabled(true);
		dp_income.setEnabled(true);
		tf_status.setEnabled(false);
	}

	public void getAllData() {
		this.rs = controller.get();
		loadTable(this.rs);
	}

	public void loadTable(ResultSet rs) {
		tb_goods.setModel(DbUtils.resultSetToTableModel(rs));
	}

	public void clear() {
		tf_name.setText("");
		tf_goods.setText("");
		tf_stock.setText("");
		tf_price.setText("");
		tf_status.setText("");
		cb_type.setSelectedIndex(0);
		dp_income.setDate(null);

		btn_update.setEnabled(false);
		btn_delete.setEnabled(false);
	}

	/**
	 * Creates new form Incoming
	 */
	public Incoming() {
		initComponents();
		getAllData();
		refresh();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_goods = new javax.swing.JTextField();
        tf_stock = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        cb_type = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_goods = new javax.swing.JTable();
        label_search = new javax.swing.JLabel();
        tf_search = new javax.swing.JTextField();
        btn_searchID = new javax.swing.JButton();
        btn_searchName = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_switch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_status = new javax.swing.JTextField();
        dp_income = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Incoming");

        jLabel2.setText("Name of Employee");

        jLabel3.setText("Good's Name");

        jLabel5.setText("Income Date");

        jLabel6.setText("Stock");

        jLabel7.setText("Price");

        cb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronic", "Clothes", "Foods & Drinks" }));

        tb_goods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_goods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_goodsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_goodsMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tb_goods);

        label_search.setText("Search Bar");

        btn_searchID.setText("Search By Name");
        btn_searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchIDActionPerformed(evt);
            }
        });

        btn_searchName.setText("Search By iD");
        btn_searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchNameActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_switch.setText("Move To Outcoming");
        btn_switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_switchActionPerformed(evt);
            }
        });

        jLabel9.setText("Status");

        tf_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_statusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_switch)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tf_price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(tf_stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(tf_goods, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(tf_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(cb_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(dp_income, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_submit)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_delete)
                                            .addComponent(btn_update))))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_search)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_searchID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_searchName)))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_search))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_searchID)
                            .addComponent(btn_searchName))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tf_goods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(dp_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_submit)
                            .addComponent(btn_update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_switch)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
		// TODO add your handling code here:
		try {
			String status = tf_status.getText();

			model.setDelete_income(status);

			boolean result = controller.delete(goods_id, model);
			if (status.equals("0")) {
				if (result) {
					JOptionPane.showMessageDialog(null, "Success Deleted Data");
					refresh();
				}
			} else{
			JOptionPane.showMessageDialog(null, "Change the status into 0 first to"
					+ "delete data");
			}
			getAllData();
		} catch (Exception ex) {
			System.err.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
		// TODO add your handling code here:
		try {
			String name = tf_name.getText();
			String goods_name = tf_goods.getText();
			String type = cb_type.getSelectedItem().toString();
			Date date = dp_income.getDate();
			String stock = tf_stock.getText();
			String price = tf_price.getText();

			model.setIncome_name(name);
			model.setGoods_name(goods_name);
			model.setCategory(type);
			model.setIncoming(date);
			model.setStock(stock);
			model.setPrice(price);

			boolean result = controller.input(model);
			Boolean check_name = logic.checkName(name);
			if (check_name) {
				if (result) {
					JOptionPane.showMessageDialog(null, "Success Submited Data");
					refresh();
				}
			} else {
				JOptionPane.showMessageDialog(null, "Fail Submited Data");
			}
			getAllData();
		} catch (Exception ex) {
			System.err.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
		// TODO add your handling code here:
		try {
			String name = tf_name.getText();
			String goods_name = tf_goods.getText();
			String type = cb_type.getSelectedItem().toString();
			Date date = dp_income.getDate();
			String stock = tf_stock.getText();
			String price = tf_price.getText();

			tf_status.setText("1"); //EVEN CHANGED IN FRAME, THE VALUE STILL 1

			model.setIncome_name(name);
			model.setGoods_name(goods_name);
			model.setCategory(type);
			model.setIncoming(date);
			model.setStock(stock);
			model.setPrice(price);

			boolean result = controller.update(goods_id, model);
			if (result) {
				JOptionPane.showMessageDialog(null, "Success Updated Data");
			} else {
				JOptionPane.showMessageDialog(null, "Fail Updated Data");
			}
			refresh();
			getAllData();
			dp_income.setEnabled(true); //AFTER CLICKED UPDATE BUTTON, THEN DP_INCOME CAN BE USED AGAIN

		} catch (Exception ex) {
			System.err.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tb_goodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_goodsMouseClicked
		// TODO add your handling code here:
		try {
			String id = helper.getValueRows(tb_goods, 0);
			String name = helper.getValueRows(tb_goods, 1);
			String goods_name = helper.getValueRows(tb_goods, 2);
			String category = helper.getValueRows(tb_goods, 3);
			String incoming = helper.getValueRows(tb_goods, 4);
			String stock = helper.getValueRows(tb_goods, 5);
			String price = helper.getValueRows(tb_goods, 6);
			String status = helper.getValueRows(tb_goods, 7);

			btn_update.setEnabled(true);
			btn_delete.setEnabled(true);

			this.goods_id = id;
			tf_name.setText(name);
			tf_goods.setText(goods_name);
			cb_type.setSelectedItem(category);
			dp_income.setDate(helper.parseStringToDatePickerFormat(incoming));
			dp_income.setEnabled(false);
			tf_status.setEnabled(true);
			tf_name.setEnabled(false); //SO IT CAN'T BE CHANGED
			tf_stock.setText(stock);
			tf_price.setText(price);
			tf_status.setText(status);

		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
    }//GEN-LAST:event_tb_goodsMouseClicked

    private void btn_searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchIDActionPerformed
		// TODO add your handling code here:
		search("name", tf_search.getText());
    }//GEN-LAST:event_btn_searchIDActionPerformed

    private void btn_searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchNameActionPerformed
		// TODO add your handling code here:
		search("id", tf_search.getText());
    }//GEN-LAST:event_btn_searchNameActionPerformed

    private void tb_goodsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_goodsMouseExited
		// TODO add your handling code here:
    }//GEN-LAST:event_tb_goodsMouseExited

    private void tf_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_statusMouseClicked
		// TODO add your handling code here:
		JOptionPane.showMessageDialog(null, "Fill in 0 to delete data, then press delete button");
    }//GEN-LAST:event_tf_statusMouseClicked

    private void btn_switchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_switchActionPerformed
		// TODO add your handling code here:
		Outcoming outcoming = new Outcoming();
		this.setVisible(false);
		outcoming.setVisible(true);
		dispose();
    }//GEN-LAST:event_btn_switchActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
		refresh();
    }//GEN-LAST:event_formMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Incoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Incoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Incoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Incoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Incoming().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_searchID;
    private javax.swing.JButton btn_searchName;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_switch;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_type;
    private org.jdesktop.swingx.JXDatePicker dp_income;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_search;
    private javax.swing.JTable tb_goods;
    private javax.swing.JTextField tf_goods;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_search;
    private javax.swing.JTextField tf_status;
    private javax.swing.JTextField tf_stock;
    // End of variables declaration//GEN-END:variables
}
